version: 2

jobs:
  setup:
    working_directory: ~/docker-kubuntu
    machine: true
    steps:
      - run:
          name: System Update
          command: |
            sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release --short --codename)-backports main restricted universe multiverse" # for jq 1.4+
            sudo apt-get update -qq
            # Remove unnecessary packages for faster dist-upgrade
            sudo apt-get remove --yes \
              build-essential \
              default-jre openjdk-7-jre-headless \
              openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless \
              gcc gcc-4.8 gfortran-4.8 \
              google-chrome-stable \
              google-cloud-sdk \
              sbt
            sudo apt-get autoremove --yes
            DEBIAN_FRONTEND=noninteractive sudo apt-get dist-upgrade --yes
            DEBIAN_FRONTEND=noninteractive sudo apt-get install --yes jq ruby-mustache
      - checkout
      - run: ./build.sh

  build-bionic:
    working_directory: ~/docker-kubuntu
    machine: true
    steps:
      - run: docker build --tag=phanect/kubuntu ./dist/18.04/
  build-xenial:
    working_directory: ~/docker-kubuntu
    machine: true
    steps:
      - run: docker build --tag=phanect/kubuntu ./dist/16.04/
  build-trusty:
    working_directory: ~/docker-kubuntu
    machine: true
    steps:
      - run: docker build --tag=phanect/kubuntu ./dist/14.04/
  build-precise:
    working_directory: ~/docker-kubuntu
    machine: true
    steps:
      - run: docker build --tag=phanect/kubuntu ./dist/12.04/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup

      - build-bionic:
          requires:
            - setup
      - build-xenial:
          requires:
            - setup
      - build-trusty:
          requires:
            - setup
      - build-precise:
          requires:
            - setup
